[platformio]
default_envs = esp32-evb-relay-test

[env:esp32-evb-relay-test]
platform = espressif32
board = esp32-evb
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -DGRIDEX_RELAY_ACTIVE_HIGH=1
