[platformio]
default_envs = tcan485

[env:tcan485]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -std=gnu++17
    -DGRIDEX_TCAN485=1
build_unflags =
    -std=gnu++11
