#!/bin/sh
# Installs a persistent OT-only systemd-networkd override from /etc/gridex env
# values. Run as root on ROCK Pi only after the management link has been
# verified. The native override intentionally wins over the vendor wildcard
# DHCP rule without modifying that vendor-managed file.
set -eu

environment_file=/etc/gridex/gridex-rockpie.env
[ -r "$environment_file" ] || {
    echo "missing $environment_file" >&2
    exit 1
}

set -a
. "$environment_file"
set +a

: "${GRIDEX_MANAGEMENT_INTERFACE:?missing GRIDEX_MANAGEMENT_INTERFACE}"
: "${GRIDEX_OT_INTERFACE:?missing GRIDEX_OT_INTERFACE}"
: "${GRIDEX_OT_ADDRESS:?missing GRIDEX_OT_ADDRESS}"
: "${GRIDEX_OT_PREFIX:?missing GRIDEX_OT_PREFIX}"

case "$GRIDEX_MANAGEMENT_INTERFACE:$GRIDEX_OT_INTERFACE" in
    *[!A-Za-z0-9_.:-]*|:) echo "invalid interface name" >&2; exit 1 ;;
esac
case "$GRIDEX_OT_PREFIX" in
    8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30) ;;
    *) echo "invalid GRIDEX_OT_PREFIX" >&2; exit 1 ;;
esac

umask 077
temporary=/etc/systemd/network/05-gridex-ot.network.tmp.$$
cat > "$temporary" <<EOF
# Generated by GrideX. Do not edit; change /etc/gridex/gridex-rockpie.env.
[Match]
Name=$GRIDEX_OT_INTERFACE

[Link]
RequiredForOnline=no

[Network]
Address=$GRIDEX_OT_ADDRESS/$GRIDEX_OT_PREFIX
DHCP=no
LinkLocalAddressing=no
IPv6AcceptRA=no
EOF

chmod 644 "$temporary"
mv "$temporary" /etc/systemd/network/05-gridex-ot.network

# Remove only the obsolete file created by earlier GrideX installer revisions.
rm -f /etc/netplan/20-gridex-dual-ethernet.yaml
networkctl reload
networkctl reconfigure "$GRIDEX_OT_INTERFACE"
