[platformio]
default_envs = esp32-evb-can

[env]
platform = espressif32
board = esp32-evb
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -std=gnu++17
    -DGRIDEX_ESP32_EVB=1
build_unflags =
    -std=gnu++11
lib_deps =
    knolleary/PubSubClient@^2.8

[env:esp32-evb-can]
build_flags =
    ${env.build_flags}
    -DGRIDEX_DEVICE_BUS_CAN=1

[env:esp32-evb-rs485]
build_flags =
    ${env.build_flags}
    -DGRIDEX_DEVICE_BUS_RS485=1
    -DGRIDEX_RS485_DIRECTION_GPIO=13

[env:esp32-evb-deye-sun100k-g03-rs485]
build_flags =
    ${env:esp32-evb-rs485.build_flags}
    -DGRIDEX_DRIVER_DEYE_SUN100K_G03_RS485=1
